const express = require('express');
const router = express.Router();
const userRoute = require('./user');
const loginRoute = require('./login');
const categoryAllRoute = require('./categoryAll');
const categorySupplierRoute = require('./categorySupplier');
const categoryPublishRoute = require('./categoryPublish');
const categoryYearRoute = require('./categoryYear');
const categoryDetailRoute = require('./categoryDetail');
const productRoute = require('./product');
const reviewRoute = require('./review');
const conversationRoute = require('./conversation');
const messageRoute = require('./message');
const cartRoute = require('./cart');
const paymentRoute = require('./payment');
const discountCodeRoute = require('./discountCode');
// const vnPayRoute = require('./vnpay');
const favoriteRoute = require('./favorite');
router.use('/user', userRoute);
router.use('/login', loginRoute);
router.use('/categoryAll', categoryAllRoute);
router.use('/categorySupplier', categorySupplierRoute);
router.use('/categoryPublish', categoryPublishRoute);
router.use('/categoryYear', categoryYearRoute);
router.use('/categoryDetail', categoryDetailRoute);
router.use('/product', productRoute);
router.use('/review', reviewRoute);
router.use('/conversation', conversationRoute);
router.use('/message', messageRoute);
router.use('/cart', cartRoute);
router.use('/payment', paymentRoute);
router.use('/discountCode', discountCodeRoute);
// router.use('/order', vnPayRoute);
router.use('/favorite', favoriteRoute);
// =================================================================

module.exports = router;
